alter table CB_DOCUMENT_IN_STRUCTURE add constraint FK_CB_DOCUMENT_IN_STRUCTURE_ON_TYPE foreign key (TYPE_ID) references CB_STRUCTURE(ID);
alter table CB_DOCUMENT_IN_STRUCTURE add constraint FK_CB_DOCUMENT_IN_STRUCTURE_ON_FILE foreign key (FILE_ID) references SYS_FILE(ID);
create index IDX_CB_DOCUMENT_IN_STRUCTURE_ON_TYPE on CB_DOCUMENT_IN_STRUCTURE (TYPE_ID);
create index IDX_CB_DOCUMENT_IN_STRUCTURE_ON_FILE on CB_DOCUMENT_IN_STRUCTURE (FILE_ID);
